    #Mana's sprites
    image mnbye = "images/mn_koikatsu/mn(bye).png"
    image mncalm = "images/m_koikatsun/mn(calm).png"
    image mnlaugh = "images/mn_koikatsu/mn(laugh).png"
    image mnconc = "images/mn_koikatsu/mn(concentrated).png"
    image mncalmsleep = "images/mn_koikatsu/mn(calmsleep).png"
    image mn = "images/mn_koikatsu/mn.png"
    image mngo = "images/mn_koikatsu/mn(go).png" #mango xDDD
    image mntricky = "images/mn_koikatsu/mn(tricky).png"
    image mntrickynude = "images/mn_koikatsu/mn(trickynude).png"
    image mnhappy = "images/mn_koikatsu/mn(happy).png"
    image mnhug = "images/mn_koikatsu/mn(hug).png"
    
    #Planya's sprites
    image pnbye = "images/pn_koikatsu/pn(bye).png"
    image pncalm = "images/pn_koikatsu/pn(calm).png"
    image pnstretch = "images/pn_koikatsu/pn(stretch).png"
    image pnlaugh = "images/pn_koikatsu/pn(laugh).png"
    image pnlove = "images/pn_koikatsu/pn(love).png"
    image pnhug = "images/pn_koikatsu/pn(hug).png"
    image pnthink = "images/pn_koikatsu/pn(think).png"
    image pnemb = "images/pn_koikatsu/pn(embarassed).png"
    image pnserious = "images/pn_koikatsu/pn(serious).png"
    image pnscared = "images/pn_koikatsu/pn(scared).png"
    image pn = "images/pn_koikatsu/pn.png"